language: java
sudo: required
jdk: oraclejdk7
before_install:
  - apt-get -qq update
  - apt-get install -y tomcat7 tomcat7-admin tomcat7-common
install: true
before_script:
  - ./conf/travis.sh
script:
  - mvn package
  - service tomcat7 restart
  - mvn tomcat7:deploy