language: java
sudo: required
jdk: oraclejdk7
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tomcat7 tomcat7-admin tomcat7-common
install: true
after_install:
  - ./conf/travis.sh
script:
  - mvn package
  - sudo service tomcat7 restart
  - mvn tomcat7:deploy